/** @type {import('tailwindcss').Config} */
export default {
  mode: "jit",
  darkMode: "class",
  content: [
    "./popup.tsx",
    "./options.tsx",
    "./tabs/**/*.{ts,tsx}",
    "./contents/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        abyss: {
          DEFAULT: "#2C3047",
          50: "#0f172a",
          100: "#712629",
          200: "#27272f",
          300: "#334155",
          400: "#475569",
          500: "#64748b",
          600: "#718096",
          700: "#818998",
          800: "#9333ea",
          900: "#a8a29e",
          950: "#c2410c",
        },
      },
    },
  },
  plugins: [require("daisyui/src/index.js")],
  daisyui: {
    themes: [
      {
        corporate: {
          primary: "#3b82f6",
          "primary-focus": "#2563eb",
          "primary-content": "#ffffff",
          secondary: "#8b5cf6",
          "secondary-focus": "#7c3aed",
          "secondary-content": "#ffffff",
          accent: "#06b6d4",
          "accent-focus": "#0891b2",
          "accent-content": "#ffffff",
          neutral: "#000000",
          "neutral-focus": "#1f2937",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f3f4f6",
          "base-300": "#e5e7eb",
          "base-content": "#374151",
          info: "#3b82f6",
          "info-content": "#ffffff",
          success: "#10b981",
          "success-content": "#ffffff",
          warning: "#f59e0b",
          "warning-content": "#000000",
          error: "#ef4444",
          "error-content": "#000000",
          border: "#d1d5db",
          input: "#f3f4f6",
          card: "#ffffff",
          skeleton: "#e5e7eb",
          "--radius-selector": "0.25rem",
          "--radius-field": "0.25rem",
          "--radius-box": "0.5rem",
          "--size-selector": "0.25rem",
          "--size-field": "0.25rem",
        },
      },
    ],
  },
};
